var shirtData = {
  'PC61': {
    'name': 'Port & Company - Adult (PC61)',
    'description': 'Heavyweight 6.1-ounce, 100% cotton (preshrunk) Our best-selling t-shirt has been voted "most popular" by groups, teams, clubs and schools across America.',
    'image': 'img/thumb_shirt.jpg',
    'cost': 3.82,
    'colors': [
      { 'color': '#84c2d4', 'name': 'Aqua Blue' },
      { 'color': '#dcdedc', 'name': 'Ash Grey' },
      { 'color': '#bcbabc', 'name': 'Athletic Heather' },
      { 'color': '#5c1a24', 'name': 'AthleticMaroon', 'dark': 'true' },
      { 'color': '#0c161c', 'name': 'Black', 'dark': 'true' },
      { 'color': '#543a24', 'name': 'Brown', 'dark': 'true' },
      { 'color': '#e47e9c', 'name': 'Candy Pink' },
      { 'color': '#8c1a2c', 'name': 'Cardinal' },
      { 'color': '#6caedc', 'name': 'Carolina Blue' },
      { 'color': '#f4d694', 'name': 'Chamois Yellow' },
      { 'color': '#2c3634', 'name': 'Charcoal' },
      { 'color': '#6c8ab4', 'name': 'Colonial Blue' },
      { 'color': '#fcf6c4', 'name': 'Daffodil Yellow' },
      { 'color': '#4c2e2c', 'name': 'Dark Chocolate Brown' },
      { 'color': '#0c322c', 'name': 'Dark Green' },
      { 'color': '#5c5e5c', 'name': 'Dark Heather Grey' },
      { 'color': '#0c56a4', 'name': 'Deep Marine' },
      { 'color': '#8cae7c', 'name': 'Dill Green' },
      { 'color': '#84765c', 'name': 'Dusty Brown' },
      { 'color': '#cc2634', 'name': 'Fiery Red' },
      { 'color': '#2c4e34', 'name': 'Forest Green' },
      { 'color': '#f4aa04', 'name': 'Gold' },
      { 'color': '#04966c', 'name': 'Jade Green' },
      { 'color': '#04825c', 'name': 'Kelly Green' },
      { 'color': '#04825c', 'name': 'Lemon Yellow' },
      { 'color': '#9cceec', 'name': 'Light Blue' },
      { 'color': '#d4bea4', 'name': 'Light Sand' },
      { 'color': '#a4c244', 'name': 'Lime' },
      { 'color': '#8c8684', 'name': 'Medium Grey' },
      { 'color': '#f4ead4', 'name': 'Natural' },
      { 'color': '#0c2e4c', 'name': 'Navy' },
      { 'color': '#444234', 'name': 'Olive' },
      { 'color': '#e45a14', 'name': 'Orange' },
      { 'color': '#f4a65c', 'name': 'Orange Sherbert' },
      { 'color': '#f4c6cc', 'name': 'Pale Pink' },
      { 'color': '#a4b674', 'name': 'Pistachio' },
      { 'color': '#2c2e6c', 'name': 'Purple' },
      { 'color': '#c4122c', 'name': 'Red' },
      { 'color': '#bc1a44', 'name': 'Rich Red' },
      { 'color': '#34529c', 'name': 'Royal' },
      { 'color': '#ac9274', 'name': 'Sand' },
      { 'color': '#dc2a7c', 'name': 'Sangria' },
      { 'color': '#446694', 'name': 'Sapphire' },
      { 'color': '#4c4e44', 'name': 'Spruce' },
      { 'color': '#4c5e74', 'name': 'Steele Blue' },
      { 'color': '#849eb4', 'name': 'Stone Wash Blue' },
      { 'color': '#a4a69c', 'name': 'Stone Wash Green' },
      { 'color': '#bc5a24', 'name': 'Texas Orange' },
      { 'color': '#5cbee4', 'name': 'Turqoise' },
      { 'color': '#446aac', 'name': 'Marine Blue' },
      { 'color': '#847aac', 'name': 'Violet' },
      { 'color': '#f4f2f4', 'name': 'White' },
      { 'color': '#fcde6c', 'name': 'Yellow' }
    ]
  },
  'longSleeveShirt': {
    'name': 'Long Sleeve Shirt',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce placerat sapien a arcu ultricies molestie. Morbi sollicitudin urna non enim tincidunt volutpat. Donec ultrices fermentum suscipit. Maecenas suscipit, lacus ac pulvinar pellentesque, purus est luctus diam, a fringilla nisi massa venenatis arcu. Donec mi turpis, pulvinar vitae tincidunt eget, posuere vel leo. Praesent at lorem in nulla rhoncus aliquam at at dolor.',
    'image': 'img/thumb_shirt.jpg',
    'cost': 4.25,
    colors: [
      { 'name': 'CadetBlue', 'color': '#5F9EA0' },
      { 'name': 'Chartreuse', 'color': '#7FFF00' },
      { 'name': 'Chocolate', 'color': '#D2691E' },
      { 'name': 'Coral', 'color': '#FF7F50' },
      { 'name': 'CornflowerBlue', 'color': '#6495ED' },
      { 'name': 'Cornsilk', 'color': '#FFF8DC' },
      { 'name': 'Crimson', 'color': '#DC143C' },
      { 'name': 'Cyan', 'color': '#00FFFF' },
      { 'name': 'DarkBlue', 'dark': 'true', 'color': '#00008B' },
      { 'name': 'DarkCyan', 'dark': 'true', 'color': '#008B8B' },
      { 'name': 'DarkGoldenRod', 'dark': 'true', 'color': '#B8860B' },
      { 'name': 'DarkGray', 'dark': 'true', 'color': '#A9A9A9' },
      { 'name': 'DarkGrey', 'dark': 'true', 'color': '#A9A9A9' },
      { 'name': 'DarkGreen', 'dark': 'true', 'color': '#006400' },
      { 'name': 'DarkKhaki', 'dark': 'true', 'color': '#BDB76B' },
      { 'name': 'DarkMagenta', 'dark': 'true', 'color': '#8B008B' },
      { 'name': 'DarkOliveGreen', 'dark': 'true', 'color': '#556B2F' },
      { 'name': 'Darkorange', 'dark': 'true', 'color': '#FF8C00' },
      { 'name': 'DarkOrchid', 'dark': 'true', 'color': '#9932CC' },
      { 'name': 'DarkRed', 'dark': 'true', 'color': '#8B0000' },
      { 'name': 'DarkSalmon', 'dark': 'true', 'color': '#E9967A' },
      { 'name': 'DarkSeaGreen', 'dark': 'true', 'color': '#8FBC8F' },
      { 'name': 'DarkSlateBlue', 'dark': 'true', 'color': '#483D8B' },
      { 'name': 'DarkSlateGray', 'color': '#2F4F4F' },
      { 'name': 'DarkSlateGrey', 'color': '#2F4F4F' },
      { 'name': 'DarkTurquoise', 'color': '#00CED1' },
      { 'name': 'DarkViolet', 'color': '#9400D3' },
      { 'name': 'DeepPink', 'color': '#FF1493' },
      { 'name': 'DeepSkyBlue', 'color': '#00BFFF' },
      { 'name': 'DimGray', 'color': '#696969' },
      { 'name': 'DimGrey', 'color': '#696969' },
      { 'name': 'DodgerBlue', 'color': '#1E90FF' }
    ]
  }
};

var surchargeDarkColor = 0.10;
var surcharge2XL = 1.00;
var surcharge3XL = 2.00;
var surcharge4XL = 3.00;
var surcharge5XL = 4.00;

var maxOrderSize = 1000;

var inkData = [
  { 'lessThan': 24, 'inkPrices': [ 2.50, 3.20, 3.90, 4.60, 5.40, 6.15 ] },
  { 'lessThan': 36, 'inkPrices': [ 1.85, 2.55, 3.25, 4.00, 4.75, 5.50 ] },
  { 'lessThan': 120, 'inkPrices': [ 1.30, 1.55, 1.75, 2.05, 2.40, 2.70 ] },
  { 'lessThan': 144, 'inkPrices': [ 1.23, 1.49, 1.72, 1.95, 2.18, 2.41 ] },
  { 'lessThan': 200, 'inkPrices': [ 1.20, 1.43, 1.64, 1.85, 2.06, 2.26 ] },
  { 'lessThan': 300, 'inkPrices': [ 1.15, 1.35, 1.55, 1.70, 1.80, 1.90 ] },
  { 'lessThan': 500, 'inkPrices': [ 1.10, 1.25, 1.45, 1.55, 1.65, 1.75 ] },
  { 'lessThan': 1000, 'inkPrices': [ 1.05, 1.15, 1.24, 1.32, 1.40, 1.48 ] },
  { 'lessThan': 2000, 'inkPrices': [ 1.00, 1.07, 1.14, 1.21, 1.28, 1.35 ] },
  { 'lessThan': 3000, 'inkPrices': [ 0.95, 1.02, 1.09, 1.15, 1.23, 1.30 ] },
  { 'lessThan': 4000, 'inkPrices': [ 0.90, 0.97, 1.04, 1.22, 1.18, 1.25 ] }
];
